#index:
#    path: /
#    controller: App\Controller\DefaultController::index

add_taxonomy:
  path: /admin/forms/{resource}/add
  controller: App\Action\Admin\Http\Forms\Add

edit_taxonomy:
  path: /admin/forms/{resource}/edit/{name}
  controller: App\Action\Admin\Http\Forms\Edit
